---
# FantasyProtection Configuration! By Enrick3344
# You Can Use & For The Color Codes.

# The Prefix That Will Be Showed Before The Message. Ex: [FantasyProtection] You are not aloud to do that here!
Prefix: "§7[§dFantasyProtection§7]"

# Protection Configuration! Add A World To Disable The Feature. Or use the command to enable/disable.
# Hunger
Hunger: []

# Break
Break: []
Break-Message: "§cYou are not allowed to break blocks here!"

# Place
Place: []
Place-Message: "§cYou are not allowed to place blocks here!"

# Drop
Drop: []
Drop-Message: "§cYou are not allowed to drop items or blocks here!"

# PVP
PVP: []
PVP-Message: "§cYou are not Allowed to PVP here!"

# Lock
Lock: []
Lock-Message: "§cYou are not allowed to do that here!"

# Damage
Damage: []

# Close
Close: []
Close-Message: "§cYou cannot go on this world! the world is closed."
...
